name: Build and Push Benchbase Image to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            platform: linux/amd64
            tag: latest-amd64
          - arch: arm64
            platform: linux/arm64
            tag: latest-arm64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone Benchbase at specific commit
        run: |
          git clone --depth 1 https://github.com/cmu-db/benchbase.git
          cd benchbase
          git fetch --depth 1 origin 4ac0750aa9ef23be6491df3e008b74010f0c2f70
          git checkout 4ac0750aa9ef23be6491df3e008b74010f0c2f70

      - name: Prepare Benchbase build context
        run: |
          cd benchbase
          mkdir -p profiles target results
          sudo chmod -R u+rwX .
          sudo chmod -R g+rwX .
          sudo chmod -R o+rwX .
          # Patch build-in-container.sh to add safe.directory
          sed -i '/mkdir -p \/profiles/a git config --global --add safe.directory /benchbase' docker/benchbase/devcontainer/build-in-container.sh
          # Patch build-full-image.sh to use cp -a instead of cp -al
          sed -i 's/cp -al/cp -a/g' docker/benchbase/build-full-image.sh

      - name: Build Benchbase Docker Image for ${{ matrix.arch }}
        run: |
          cd benchbase
          export SKIP_TESTS=true
          export BENCHBASE_PROFILES=postgres
          export DOCKER_BUILDKIT=1
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          ./docker/benchbase/build-full-image.sh --platform=${{ matrix.platform }}
          # Tag the image for GHCR
          docker tag benchbase:latest ghcr.io/neondatabase-labs/benchbase:${{ matrix.tag }}

      - name: Push Benchbase Docker Image for ${{ matrix.arch }}
        run: |
          docker push ghcr.io/neondatabase-labs/benchbase:${{ matrix.tag }}

  manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and Push Multi-Arch Manifest
        run: |
          docker manifest create ghcr.io/neondatabase-labs/benchbase:latest \
            --amend ghcr.io/neondatabase-labs/benchbase:latest-amd64 \
            --amend ghcr.io/neondatabase-labs/benchbase:latest-arm64
          docker manifest push ghcr.io/neondatabase-labs/benchbase:latest

      - name: Log out from GHCR
        run: docker logout ghcr.io 